// Date: 9.6.2015 2:24:46 PM
// Template version 1.1
// Java generated by Techne
// Keep in mind that you still need to fill in some blanks
// - ZeuX






package ga.warixmods.agkm.client.model;

import net.minecraft.client.model.ModelBase;
import net.minecraft.client.model.ModelRenderer;
import net.minecraft.entity.Entity;

public class ModelRocketLauncherRM extends ModelBase
{
  //fields
    ModelRenderer head;
    ModelRenderer neck;
    ModelRenderer body;
  
  public ModelRocketLauncherRM()
  {
    textureWidth = 64;
    textureHeight = 32;
    
    head = new ModelRenderer(this, 0, 0);
    head.addBox(-3.5F, -5F, -3.5F, 7, 5, 7);
    head.setRotationPoint(-0.5F, -3F, -0.5F);
    head.setTextureSize(64, 32);
    head.mirror = true;
    setRotation(head, 0F, 0F, 0F);
    neck = new ModelRenderer(this, 28, 8);
    neck.addBox(0F, 0F, 0F, 1, 3, 1);
    neck.setRotationPoint(-1F, -3F, -1F);
    neck.setTextureSize(64, 32);
    neck.mirror = true;
    setRotation(neck, 0F, 0F, 0F);
    body = new ModelRenderer(this, 28, 0);
    body.addBox(0F, 0F, 0F, 7, 1, 7);
    body.setRotationPoint(-4F, 0F, -4F);
    body.setTextureSize(64, 32);
    body.mirror = true;
    setRotation(body, 0F, 0F, 0F);
  }
  
  public void render(Entity entity, float f, float f1, float f2, float f3, float f4, float f5)
  {
    super.render(entity, f, f1, f2, f3, f4, f5);
    setRotationAngles(entity,f, f1, f2, f3, f4, f5);
    head.render(f5);
    neck.render(f5);
    body.render(f5);
  }
  
  private void setRotation(ModelRenderer model, float x, float y, float z)
  {
    model.rotateAngleX = x;
    model.rotateAngleY = y;
    model.rotateAngleZ = z;
  }
  
  public void setRotationAngles(Entity entity,float f, float f1, float f2, float f3, float f4, float f5)
  {
    super.setRotationAngles(f, f1, f2, f3, f4, f5,entity);
  }

}
